# Generated by Django 3.1.1 on 2020-12-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.AutoField(db_column='CustID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=15)),
                ('phone', models.CharField(db_column='Phone', max_length=14)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(db_column='Type')),
                ('category', models.IntegerField(db_column='Category')),
                ('weekly', models.IntegerField(db_column='Weekly')),
                ('daily', models.IntegerField(db_column='Daily')),
            ],
            options={
                'db_table': 'rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.CharField(db_column='StartDate', max_length=10)),
                ('orderdate', models.CharField(db_column='OrderDate', max_length=10)),
                ('rentaltype', models.IntegerField(blank=True, db_column='RentalType', null=True)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('returndate', models.CharField(db_column='ReturnDate', max_length=10)),
                ('totalamount', models.TextField(db_column='TotalAmount')),
                ('paymentdate', models.CharField(blank=True, db_column='PaymentDate', max_length=10, null=True)),
                ('returned', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleid', models.CharField(blank=True, db_column='VehicleID', max_length=17, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=15)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('type', models.IntegerField(db_column='Type')),
                ('category', models.IntegerField(blank=True, db_column='Category', null=True)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
    ]
